version: "3"
services:
  sillytavern-extras:
#    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
#              either specify below which, or above how many. not both.
#              device_ids: ['1'] 
              capabilities: [gpu]
    image: cohee1207/sillytavern-extras
    build:
      context: ../
      dockerfile: docker/Dockerfile
      args:
        REQUIREMENTS: requirements.txt
        MODULES: caption,summarize,classify
#        REQUIREMENTS: "requirements.txt -r requirements-rvc.txt"
#        MODULES: caption,summarize,classify,rvc
    volumes:
      #- "./chromadb:/chromadb"
      - "./cache:/root/.cache"
      - "../api_key.txt:/sillytavern-extras/api_key.txt:rw"
    ports:
      - "5100:5100"
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    command: python server.py --enable-modules=caption,summarize,classify
#    command: python server.py --enable-modules=caption,summarize,classify,rvc
